name: GitHub CI

# Triggers
on:
  push:
      branches:
        - main

  # Allows workflow runs manually from the Actions tab
  workflow_dispatch:
      

jobs:
  Python-Build-Actions:
    name: Checks Python build success
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Pip env build
        timeout-minutes: 2
        run: pip install -r requirements.txt
      - run: echo "Job status '${{ job.status }}'."
